on: [push, pull_request]

name: Run unit tests

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Ubuntu Latest GCC", 
            os: ubuntu-latest,
            cov: false
          }
        - {
            name: "Ubuntu Latest GCC, coverage enabled", 
            os: ubuntu-latest,
            cov: true
          }
        - {
            name: "macOS Latest Clang", 
            os: macos-latest
          }

    steps:
    - uses: actions/checkout@v1

    - name: Get latest CMake
      uses: lukka/get-cmake@latest

    - name: Configure the build
      if: ${{ matrix.config.cov == false }}
      run: cmake -S . 

    - name: Configure the build with coverage
      if: ${{ matrix.config.cov == true }}
      run: cmake -S . -DCODE_COVERAGE=ON

    - name: Build the tests
      run: cmake --build .

    - name: Run the tests
      run: ctest

    - name: Generate code coverage
      if: ${{ matrix.config.cov == true }}
      run: gcov tests/src/*.cpp

    - name: Upload to Codecov
      if: ${{ matrix.config.cov == true }}
      uses: codecov/codecov-action@v1
      with:
        directory: tests/src
